tomcat8:
    image: tomcat:8.0.21-jre8
    ports:
        - "8080:8080"
    volumes:
        - tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
        - /tmp/tomcatLogs:/usr/local/tomcat/logs/